#!/bin/bash
#
# Generate authentication file for WindMill
#

# If /run directory exists, the installation is a NethServer 6 otherwise it is a NethServer 7
if [ -d /run ]; then
    CREDENTIAL_FILE=/run/don/credentials
else
    CREDENTIAL_FILE=/var/run/don/credentials
fi

if [ ! -d $(dirname $CREDENTIAL_FILE) ]; then
    mkdir -p $(dirname $CREDENTIAL_FILE)
fi

/sbin/e-smith/config getprop don SystemId > $CREDENTIAL_FILE
/usr/bin/uuidgen >> $CREDENTIAL_FILE
