#!/bin/bash
#
# Generate authentication file for WindMill
#

CREDENTIAL_FILE=/run/don/credentials

if [ ! -d $(dirname $CREDENTIAL_FILE) ]; then
    mkdir -p $(dirname $CREDENTIAL_FILE)
fi

/sbin/e-smith/config getprop don SystemId > $CREDENTIAL_FILE
/usr/bin/uuidgen >> $CREDENTIAL_FILE
