#!/bin/bash
#
# Generate authentication file for WindMill
#

/sbin/e-smith/config getprop sysconfig Version  | grep -q '^7'

if [ $? -eq 0 ]; then
    CREDENTIAL_FILE=/run/don/credentials
else
    CREDENTIAL_FILE=/var/run/don/credentials
fi

if [ ! -d $(dirname $CREDENTIAL_FILE) ]; then
    mkdir -p $(dirname $CREDENTIAL_FILE)
fi

/sbin/e-smith/config getprop don SystemId > $CREDENTIAL_FILE
/usr/bin/uuidgen >> $CREDENTIAL_FILE
